#!/usr/bin/env bash

# script/fix: Run lint:fix scripts.

set -e

cd "$(dirname "$0")/.."

# Install NPM dependencies if node_modules directory doesn't exist
if [ -f "package.json" ]; then
    if [ ! -d "node_modules" ]; then
        echo "==> Installing NPM dependencies..."
        npm install --silent
    fi

    # Check if the npm script "lint:fix" exists and run it
    if npm run | grep -q -P "^\s+lint:fix$"; then
        echo "==> Running NPM lint:fix..."
        npm run lint:fix
    else
        echo "===> NPM lint:fix script not defined"
    fi
fi

# Install Composer dependencies if vendor directory doesn't exist
if [ -f "composer.json" ]; then
    if [ ! -d "vendor" ]; then
        echo "==> Installing Composer dependencies..."
        composer install --no-interaction --prefer-dist
    fi

    # Check if the composer script "lint:fix" exists and run it
    if composer run-script --list | grep -q -P "^\s+lint:fix\s+"; then
        echo "==> Running Composer lint:fix..."
        composer lint:fix
    else
        echo "===> Composer lint:fix script not defined"
    fi
fi
