#!/usr/bin/env bash

# script/setup: Set up application to initial state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

# Set up DB if the script exists
if [ -f "script/setup_db.sh" ]; then
    echo "==> Setting up DB..."
    script/setup_db.sh
fi

# Set up environment variables if the .env file exists
if [ -f ".env" ]; then
    echo "==> Setting up environment variables..."
    source .env
fi

# Provide a PDepend summary if the script exists
if [ -f "script/run_pdepend.sh" ]; then
    echo "==> Running pdepend..."
    script/run_pdepend.sh
fi

echo "==> Repo is now ready to go!"
