#!/usr/bin/env bash

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

# Update DB if the script exists
if [ -f "script/update_db.sh" ]; then
    echo "==> Updating DB..."
    script/update_db.sh
fi

# Update environment variables if the .env file exists
if [ -f ".env" ]; then
    echo "==> Setting up environment variables..."
    source .env
fi

# Provide a PDepend summary if the script exists
if [ -f "script/run_pdepend.sh" ]; then
    echo "==> Running pdepend..."
    script/run_pdepend.sh
fi

echo "==> Repo is now ready to go!"
